name: "Bug Report"
description: "Report a bug to help us improve DevSetup"
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting a bug!
        Please provide enough detail to help us reproduce and fix the issue quickly.

  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "Describe the bug clearly and concisely."
      placeholder: |
        What is the incorrect behavior and what should happen instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide step-by-step instructions to reproduce the bug."
      placeholder: |
        1. Go to '...'
        2. Click '...'
        3. Observe '...'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is this bug?"
      options:
        - "Low - Minor issue, workaround available"
        - "Medium - Affects functionality but not critical"
        - "High - Major functionality broken"
        - "Critical - Application unusable or data loss"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Provide key environment details (OS, browser, project version)."
      placeholder: |
        • OS: 
        • Browser: 
        • DevSetup Version:
    validations:
      required: true
